### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by vmario89** [deepinthewoods/Boxes.py-Windows-Binaries#1]
Hey dude,
this repo is great to make it work with InkScape 0.92.4. Got it running - i had to change the line in each inx file

`    <dependency type="executable" location="extensions">boxes.exe</dependency>`

. Can you explain how you made this port to a single exe file? I'd like to do this with recent boxes.py

regards, Mario

**Comment by deepinthewoods** [comment]
The exe file is made with pyInstaller.

However, Boxes uses reflection to run the actual generators, so they are not included in the generated exe. To get around this I ended up building an imports.py file which just contained
`import ClosedBox`
`import AngledBox`
`etc`

and then passing that into 
`pyInstaller --hidden-import=imports.py`

**Comment by vmario89** [comment]
Hi, after trying for hours i am not getting to finish it. I already tried Python 2.7.17, Python 3.75 on Windows and Ubuntu 16/18 WSL :-(

i attached my procedure(s) on how i  did. I appreciate if you could review them maybe.

regards and thanks, Mario

[EDF-55019406-111119-2259-164.pdf](https://github.com/deepinthewoods/Boxes.py-Windows-Binaries/files/3833393/EDF-55019406-111119-2259-164.pdf)
[EDF-55019385-111119-2257-162.pdf](https://github.com/deepinthewoods/Boxes.py-Windows-Binaries/files/3833394/EDF-55019385-111119-2257-162.pdf)

**Comment by vmario89** [comment]
ps: final stacktrace when using my boxes.exe compile, the inkscape output will be

```
C:\Users\mario\AppData\Local\Temp\_MEI148522\distutils\dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
usage: boxes.exe [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: boxes.exe --help [cmd1 cmd2 ...]
   or: boxes.exe --help-commands
   or: boxes.exe cmd --help

error: option --generator not recognized

```

**Comment by deepinthewoods** [comment]
Wsl will not work, it needs to be running on windows. Wsl is just a Linux VM. 
Make sure you can run `python boxes closedbox` in command prompt from the scripts folder.
THEN the exe will still give a "generator not found" error because the actual generators (closedbox.py etc) are being accessed via reflection and not with a normal import statement. 

I'm looking into it.

**Comment by deepinthewoods** [comment]
Update is up now

**Comment by vmario89** [comment]
Hi. thanks a lot! 

I know how WSL works. I used WSL to run the setup.py to the end. this generates the inx files. Because that step does not work on Windows (or i dont get how it works)

To make boxes.exe i know that you need Windows (or WINE). I am still stucking at the point to configure PyInstaller properly. 

I tried your command

```
cd C:\Users\mario\Downloads\boxes-master\scripts\
python boxes closedbox
```

this returns

> Traceback (most recent call last):
>   File "boxes", line 24, in <module>
>     import boxes
>   File "C:\Users\mario\AppData\Local\Programs\Python\Python37\lib\site-packages\boxes-0.1-py3.7.egg\boxes\__init__.py", line 18, in <module>
>     import cairocffi
>   File "C:\Users\mario\AppData\Local\Programs\Python\Python37\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
>     ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
>   File "C:\Users\mario\AppData\Local\Programs\Python\Python37\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
>     raise OSError(error_message)  # pragma: no cover
> OSError: no library called "cairo" was found
> no library called "libcairo-2" was found
> cannot load library 'libcairo.so': error 0x7e
> cannot load library 'libcairo.2.dylib': error 0x7e
> cannot load library 'libcairo-2.dll': error 0x7e

But libcairo is installed: "Requirement already satisfied"
```
pip3 install pycairo
pip3 install cairocffi
```

**Comment by deepinthewoods** [comment]
Yeah I have had lots of problems with Cairo. This most recent time, I ended
up doing pip uninstall and then reinstalling from whl files. These are the
instructions I followed https
://florianfesti.github.io/boxes/html/install/windows.html
<https://florianfesti.github.io/boxes/html/install/windows.html>

**Comment by deepinthewoods** [comment]
You can just run
‘Python setup.py --build‘
Etc

**Comment by vmario89** [comment]
Hi, i started again to find out how to make the executable. I got a few things right now. I was able to install cairo correctly by using the wheel files.

`python scripts\boxes closedbox` returns box.svg correctly now. I can view that generated file in InkScape and its looks well. 

The only thing that still fails is the PyInstaller executable boxes.exe from dist/. The bug i am not able to fix right now is when running extension from inkscape:
![grafik](https://user-images.githubusercontent.com/5631071/72683781-a0022c80-3ada-11ea-9d98-c725f86f68ae.png)


```
> Traceback (most recent call last):
>   File "scripts\boxes", line 24, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\Users\mario\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
>     exec(bytecode, module.__dict__)
>   File "boxes\__init__.py", line 18, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\Users\mario\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\cairocffi\__init__.py", line 19, in <module>
>   File "pathlib.py", line 1216, in read_text
>   File "pathlib.py", line 1203, in open
>   File "pathlib.py", line 1058, in _opener
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mario\\AppData\\Local\\Temp\\_MEI24922\\cairocffi\\VERSION
```

I think there is some issue with cairo version and the way how to embed the import with PyInstaller. The official documentation from Florian Festi says to use Cairocfffi 1.0.2. I used 1.1.0 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#cairocffi because there is no older one. But the git repository of boxes.py uses explicit requirement: **cairocffi==0.8.0**

How did you deal with this to make it work?

I updated my documentation how i did here: https://wiki.fablabchemnitz.de/display/FCT/Boxes.py+%28Python+3.7.6%29+on+Windows

cheers, Mario

**Comment by vmario89** [comment]
finally i got it:

this command will make a working built:

`del /Q dist\ & del /Q build\ & py -3.7 -m PyInstaller scripts\boxes --add-data="boxes;boxes" --hidden-import decimal -i=static\favicon.ico -n=boxes --clean --onefile --windowed`
